services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Comment this out in production
    # volumes:
    #   - .:/app
    #   - /app/node_modules
